Projeto 1 - IA_2022/2
Vitor Caligaris Figueira -> RA: 790743 // 
Descricao: 

*   O algoritmo proposto a seguir foi baseado no algorimo genetico proposto pelo professor Ricardo Cerri para resolver o problema de custos da mochila.
*    Esse algoritmo foi adaptado pelo autor para resolver o problema das 8 rainhas, como discutido em aula. Alterando obviamente a funcao de fitness e os parametros em geral.
*   O durante a resolucao os comentarios presentes explicam melhor cada passo.








In [1]:
# Importando bibliotecas padrao
import numpy as np
import random

In [28]:
# Define numero de individuos e codificacao do individuo como sendo um vetor com 8 posicoes
# em que cada posicao indica uma coluna e o numero dentro indica a linha que a rainha foi posicionada.
num_individuos = 1000
len_indv = 8
populacao_inicial = np.zeros((num_individuos, len_indv), dtype=int)
# Ja cria primeira geracao de individuos e os printa.
for i in range(num_individuos):
  for j in range(len_indv):
    populacao_inicial[i][j] = random.randint(1,len_indv)

for i in range(num_individuos):
  print(populacao_inicial[i])

[7 7 2 6 5 2 6 2]
[7 7 2 5 2 7 1 3]
[4 6 1 6 8 6 1 6]
[5 1 3 8 7 2 5 2]
[1 7 4 6 4 5 6 3]
[6 3 6 5 5 1 3 7]
[2 1 6 5 3 8 1 8]
[6 3 7 2 7 8 2 5]
[6 1 2 4 7 6 3 4]
[4 4 8 5 5 5 4 7]
[7 4 3 8 6 4 8 2]
[4 5 6 2 6 5 2 5]
[3 6 6 7 4 3 1 4]
[8 5 1 8 7 3 6 4]
[4 6 1 3 2 7 8 2]
[1 3 8 1 6 4 2 1]
[4 7 5 7 1 6 4 4]
[7 4 8 2 7 3 8 6]
[8 6 4 7 7 5 8 1]
[4 8 3 2 8 2 5 3]
[4 8 8 5 7 7 1 7]
[4 8 4 5 8 3 3 1]
[2 3 7 3 8 2 4 4]
[8 3 7 6 4 4 3 5]
[2 6 1 8 3 1 1 2]
[3 4 4 6 3 2 3 1]
[1 4 1 4 1 1 1 3]
[3 2 2 5 1 4 4 5]
[5 6 3 3 5 7 1 4]
[1 1 6 1 7 2 1 3]
[7 8 6 5 1 1 8 1]
[7 6 8 1 3 6 1 2]
[2 1 2 1 6 5 5 5]
[7 3 7 5 8 5 8 4]
[7 5 2 4 2 6 6 4]
[3 5 7 2 3 6 2 3]
[4 7 2 8 8 1 5 7]
[4 6 8 7 8 6 8 7]
[2 7 1 8 1 2 1 8]
[4 2 8 4 8 8 6 7]
[6 1 7 3 5 6 5 2]
[2 4 4 2 8 3 5 3]
[1 5 5 8 7 4 3 3]
[8 1 1 1 1 8 4 7]
[6 2 8 3 3 4 5 3]
[5 2 1 8 4 2 6 8]
[2 1 5 1 1 3 3 8]
[6 4 4 1 2 7 6 5]
[4 4 2 5 1 7 6 8]
[1 3 7 4 4 4 4 1]
[3 2 1 5 7 6 4 1]
[4 3 7 1 7 8 3 2]
[4 1 1 4 6 1 6 8]
[4 3 5 1 8 7 2 6]
[6 2 1 3 2 4 4 4]
[3 8 2 4 5

In [3]:
# Definicao da funcao de fitness, ela retorna o numero de rainhas que estao se atacando.
def fitness(ind):
  f=0; #f contabiliza pares de rainhas atacantes.

  for i in range(len_indv-1):
    k=1
    # Para cada par de rainhas vetor sera checado se elas se atacam.
    for j in range(i+1,len_indv):

      if(ind[i]==ind[j]): # Checa se esta na mesma linha.
        f+=1
      if(ind[i]==ind[j]+k): # Checa se esta na mesma diagonal superior.
        f+=1
      if(ind[i]==ind[j]-k): # Checa se esta na mesma diagonal inferior.
        f+=1

      k+=1

  return f

# retona_fitness atribui um valor de fitness para todos os membros da populacao passada como parametro da funcao.
def retorna_fitness(populacao):
  
  fit = []
  
  for i in range(num_individuos):
    f = fitness(populacao[i])
    fit.append(f)

  return fit

In [4]:
# Metodo de selecao por torneio escolhe 3 individuos e retorna os 2 mais aptos, ou seja, com menor valor fitness.
def selecao_torneio(fitnesses):
  
  ind1 = -1
  ind2 = -1

  while ind1 == ind2:
    # Torneio 1
    sorteados = random.sample(range(0, num_individuos), 2)
    if fitnesses[sorteados[0]] < fitnesses[sorteados[1]]:
      ind1 = sorteados[0]
    else:
      ind1 = sorteados[1]

    # Torneio 2
    sorteados = random.sample(range(0, num_individuos), 2)
    if fitnesses[sorteados[0]] < fitnesses[sorteados[1]]:
      ind2 = sorteados[0]
    else:
      ind2 = sorteados[1]  
        
  return ind1,ind2    


In [5]:
# Funcao para definir o cruzamento entre dois cromossomos, o cruzamento eh sempre em um ponto unico sorteado aleatoriamente.
def cruzamento(ids,populacao):
  
  ponto = random.randint(1, len_indv-1)

  pai1 = populacao[ids[0]]
  pai2 = populacao[ids[1]]

  filho1 = np.concatenate([pai1[:ponto],pai2[ponto:]])
  filho2 = np.concatenate([pai2[:ponto],pai1[ponto:]])

  return filho1,filho2

In [6]:
# Seleciona sempre os individuos mais aptos, com menor fitness, para irem direto para proxima geracao.
def elitismo(fitnesses):

  id1 = fitnesses.index(min(fitnesses))

  fitnesses.pop(id1)
  id2 = fitnesses.index(min(fitnesses))

  return id1,id2

In [7]:
# Realiza uma mutacao aleatoria em um dos pontos do cromossomo de acordo com uma taxada especificada nos paramentros.
def mutacao(filhos, taxa):

  for i in range(len(filhos)):
    if random.random() < taxa:
      pos = random.randint(0, len_indv-1)
      filhos[i][pos] = random.randint(1,len_indv)

  return filhos

In [29]:
# Número de gerações
num_geracoes = 25

# Fitness e peso do indivíduo ótimo
fitness_otimo = 0

for it in range(num_geracoes):
  # Nova populacao vazia
  nova_populacao = np.zeros((num_individuos,len_indv), dtype=int)

  # Calcula o fitness da população
  fit = retorna_fitness(populacao_inicial)
  #print(fit)

  # Imprime o melhor individuo da geracao atual
  id_melhor = fit.index(min(fit))
  print("Solucao da geracao", it, ":",'  '.join(map(str,populacao_inicial[id_melhor])), "Fitness da solucao = ",fit[id_melhor])
  print()
  # Caso o fitness chegue a 0 quer dizer que uma solucao ja foi encontrada e o algoritmo pode parar
  if(fit[id_melhor] == fitness_otimo):
    break;
  # Elitismo
  elite = elitismo(fit.copy()) # Copiando por causa da referencia do vetor
  nova_populacao[0] = populacao_inicial[elite[0]]
  nova_populacao[1] = populacao_inicial[elite[1]]

  # Gera os filhos restantes para completar a população
  num_filhos = 2
  while num_filhos < num_individuos:

    # Seleção por torneio
    ind_vencedores = selecao_torneio(fit)
    
    # Cruzamento
    filhos = cruzamento(ind_vencedores,populacao_inicial)

    # Mutacao (50% de chance de mutação em cada indivíduo)
    filhos = mutacao(filhos,0.5)

    # Coloca os filhos na nova população
    nova_populacao[num_filhos] = filhos[0]
    nova_populacao[num_filhos+1] = filhos[1]

    # Aumenta o número de filhod
    num_filhos = num_filhos + 2

  # Substitui a populacao antiga pela atual
  populacao_inicial = nova_populacao.copy()
print("Solucao encontrada na geracao", it, ":",'  '.join(map(str,populacao_inicial[id_melhor])), "Fitness da solucao = ",fit[id_melhor])

Solucao da geracao 0 : 8  1  4  4  7  5  3  6 Fitness da solucao =  2

Solucao da geracao 1 : 5  8  2  4  7  3  8  6 Fitness da solucao =  1

Solucao da geracao 2 : 5  8  2  4  7  3  8  6 Fitness da solucao =  1

Solucao da geracao 3 : 5  8  2  4  7  3  8  6 Fitness da solucao =  1

Solucao da geracao 4 : 5  8  2  4  7  3  8  6 Fitness da solucao =  1

Solucao da geracao 5 : 5  8  2  4  7  3  8  6 Fitness da solucao =  1

Solucao da geracao 6 : 5  8  2  4  7  3  8  6 Fitness da solucao =  1

Solucao da geracao 7 : 5  8  2  4  7  3  8  6 Fitness da solucao =  1

Solucao da geracao 8 : 5  8  2  4  7  3  8  6 Fitness da solucao =  1

Solucao da geracao 9 : 5  8  2  4  7  3  8  6 Fitness da solucao =  1

Solucao da geracao 10 : 5  8  2  4  7  3  8  6 Fitness da solucao =  1

Solucao da geracao 11 : 5  8  2  4  7  3  8  6 Fitness da solucao =  1

Solucao da geracao 12 : 5  8  2  4  7  3  8  6 Fitness da solucao =  1

Solucao da geracao 13 : 5  8  2  4  7  3  8  6 Fitness da solucao =  1

So